name: Artifact as cache

on: [push]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install
      run: |
        npm install
  store:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install
      run: |
        npm install
    - name: Upload
      uses: actions/upload-artifact@master
      with:
        name: node_modules
        path: node_modules
  restore:
    runs-on: ubuntu-latest
    needs: store
    steps:
    - uses: actions/checkout@v1
    - name: Download
      uses: actions/download-artifact@master
      with:
        name: node_modules
        path: node_modules
    - name: Install
      run: |
        npm install
