on: push
name: commit and push
jobs:
  build:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          ref: gh-pages
      - name: commit
        run: |
          echo '```' > github_event.md
          echo '${{toJson(github)}}' | jq . >> github_event.md
          echo '```' >> github_event.md
          git add github_event.md
          git -c user.name=gh-pages -c user.email=github@users.noreply.github.com commit -m "update"
      - name: push
        run: |
          git push 'https://yasuhiroki:${{ secrets.GITHUB_TOKEN }}@github.com/yasuhiroki/enjoy-github-actions.git' gh-pages:gh-pages
