on: push
name: commands
jobs:
  command:
    runs-on: ubuntu-latest
    steps:
      - name: print env
        run: |
          env | sort
      - name: add-path
        env:
          # ::add-path:: command is disabled by default
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        run: |
          echo ::add-path::/yasuhiroki
      - name: set-env
        env:
          # ::set-env:: command is disabled by default
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        run: |
          echo ::set-env name=NOW::$(date)
      - name: echo $NOW
        run: |
          echo $NOW
      - name: print env
        run: |
          env | sort
      - name: debug (false)
        run: |
          echo ::debug::debug log false
      - name: debug (true)
        env:
          # This env is not working, GitHub Actions debug log become possible by Secrets in Settings
          ACTIONS_STEP_DEBUG: true
        run: |
          echo ::debug::debug log true
