on: commit_comment
name: commit_comment event
jobs:
  build:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: env
        run: |
          env | sort
      - name: event
        run: |
          cat $GITHUB_EVENT_PATH | jq .
