on: push
name: matrix container2
jobs:
  build:
    name: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image_version: [ '2.5', '2.6' ]
    container:
      image: ruby:${{ matrix.image_version }}
    steps:
      - name: ruby version
        run: ruby -v
