name: Parallel

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [0, 1, 2]
    steps:
    - name: Echo
      run: |
        mkdir -p out
        echo ${{ matrix.node }} > out/${{ matrix.node }}.txt
    - name: Upload
      uses: actions/upload-artifact@master
      with:
        name: out
        path: out
    - name: Download
      uses: actions/download-artifact@master
      with:
        name: out
    - name: Print
      run: |
        ls out
        cat out/*
  result:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download
      uses: actions/download-artifact@master
      with:
        name: out
        path: out
    - name: Print
      run: |
        ls
        ls out
        cat out/*
