on: push
name: push event
jobs:
  build:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: env
        run: |
          env | sort
      - name: event
        run: |
          cat $GITHUB_EVENT_PATH | jq .
      - name: add-path
        run: |
          echo ::add-path::/yasuhiroki
      - name: env
        run: |
          env | sort
      - name: debug (false)
        run: |
          echo ::debug::debug log false
      - name: debug (true)
        env:
          # This env is not working, GitHub Actions debug log become possible by Secrets in Settings
          ACTIONS_STEP_DEBUG: true
        run: |
          echo ::debug::debug log true
