on:
  schedule:
    - cron: 0 0 * * *
name: stale
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'stale issue'
        stale-pr-message: 'stale pull request'
        days-before-stale: 1
        days-before-close: 1
